### ISSUE TITLE
libraries?

### ISSUE THREAD

**Issue by catx23** [dzharii/awesome-typescript#29]
Hi,
is there a reason why there are no libraries in this collection? Me as TS developer I am rather interested to find good libraries written in TS rather than the very basics like IDEs or links to related topics. There is currently pretty much no real resource.
thanks
g

**Comment by dzharii** [comment]
Hi @xblox, 

Well, this sounds as a great idea and I was thinking about this but... 
the question is what should we include? If we are talking about the libraries that support typescript, 
then this should include all libraries at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). 
If I include all of them, the list would be huge and overwhelming. 

This is why I would rather put a link to someone's else collection of libraries, rather than include 
every library to this list. 

@xblox if you know any of such lists, please feel free to send a pull request.

Kind regards, 
@dzharii

**Comment by xblox** [comment]
hi,
well, not so sure how DefinitelyTyped is real TypeScript but you might be right. To me, I'd still appreciate a full stack in Typescript. I know a few only libs only, for core, fs and orm and acl. I'd be happy to know more :-)

**Comment by chimon2000** [comment]
I think having a section for libraries written in TypeScript would be extremely useful.

**Comment by marpstar** [comment]
libraries like [TypeOrm](https://github.com/typeorm/typeorm) and [Inversify](https://github.com/inversify/InversifyJS/), which are written exclusively in TypeScript, should definitely be on this list.

**Comment by totano** [comment]
[RxJS](http://reactivex.io/rxjs/), [Cycle.js](https://cycle.js.org/) and its underlying streams library [xstream](http://staltz.github.io/xstream/), [TypeMoq](https://github.com/florinn/typemoq) could be added as well

**Comment by dzharii** [comment]
Hi @totano, 
Use your best judgement to decide what category those libraries belong to ;)
I am looking forward for your PR.

**Comment by totano** [comment]
created [PR](https://github.com/dzharii/awesome-typescript/pull/49)
